# Generated by Django 4.2.3 on 2024-04-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0002_alter_menu_main_menu_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='main_menu',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeMenu.menu'),
        ),
    ]
